export const GET_DEMO_REQUEST = 'GET_DEMO_REQUEST';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';

export const START_GET_OAUTH_TOKEN = 'START_GET_OAUTH_TOKEN';
export const SUCCESS_GET_OAUTH_TOKEN = 'SUCCESS_GET_OAUTH_TOKEN';
export const ERROR_GET_OATUH_TOKEN = 'ERROR_GET_OATUH_TOKEN';

export const START_GET_PROFILE_DATA = 'START_GET_PROFILE_DATA';
export const SUCCESS_GET_PROFILE_DATA = 'SUCCESS_GET_PROFILE_DATA';
export const ERROR_GET_PROFILE_DATA = 'ERROR_GET_PROFILE_DATA';

export const START_GET_PROFILE_REPOS = 'START_GET_PROFILE_REPOS';
export const SUCCESS_GET_PROFILE_REPOS = 'SUCCESS_GET_PROFILE_REPOS';
export const ERROR_GET_PROFILE_REPOS = 'ERROR_GET_PROFILE_REPOS';
